### ISSUE TITLE
Hyperlink in Jupyterlab links to 404

### ISSUE THREAD

**Issue by foxale** [neptune-ml/neptune-notebooks#16]
It links to [https://github.com/neptune.ml/neptune-notebooks](https://github.com/neptune.ml/neptune-notebooks). 
Just change _neptune.ml_ to _neptune-ml_ and it'll be fine.
 
![image](https://user-images.githubusercontent.com/14327763/62457998-31bfec80-b77c-11e9-852c-fa3615e8eba6.png)

**Comment by kamil-kaczmarek** [comment]
Hi @foxale thanks for that! We will change it.

BTW: please join us on https://spectrum.chat/neptune-community?tab=posts -> it is great place to discuss Neptune with us :)

**Comment by lukasz-walkiewicz** [comment]
Fixed in #19
